/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Coti' at '8/2/16 10:53 AM' with Gradle 2.14
 *
 * @author Coti, @date 8/2/16 10:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
